### ISSUE TITLE
Issue with shared authorizers

### ISSUE THREAD

**Issue by AdriaFret** [completecoding/serverless-auto-swagger#107]
Hello! We are having some troubles trying to implement the lambdaAuthorizer in the swagger endpoints. We have a microservices architechture, our authorizer is in a separated microservice and we can use this authorizer ( via output variable) in our lambdas. Here is a code snipet of how we use this authorizer in our lambdas:

![image](https://user-images.githubusercontent.com/92299908/203778387-539def04-7245-4174-bb29-21dbd8c381f7.png)

The idea that we had is to reuse this authorizer for the lambdaAuthorizer section but we can't figure it out why it ain't working (maybe we are missunderstanding or doing something wrong).

Thank you for your time in advance.

**Comment by AdriaFret** [comment]
Yes for sure, thats how we tried to configure it but we couldn't figure it out a way to make it work:
<img width="623" alt="image" src="https://user-images.githubusercontent.com/92299908/207634553-6f62dd02-baeb-45b7-a14b-130b0acf6358.png">

**Comment by bfaulk96** [comment]
Could you try making `lambdaAuthorizer` the same object that you're using in your http events, i.e.

```yaml
custom:
  ...
  customAuthorizer:
    type: COGNITO_USER_POOLS
    authorizerId: !ImportValue authorizer
  autoswagger:
    ...
    lambdaAuthorizer: ${self:custom.customAuthorizer}

functions:
  ...
  test:
    ...
    events:
      - http:
          ...
          authorizer: ${self:custom.customAuthorizer}
```

This was my use-case when I added this feature. If this doesn't work, I honestly don't know a ton about authorizers, so I don't know if more complex scenarios are possible.
