### ISSUE TITLE
Using external library types results in reference error

### ISSUE THREAD

**Issue by phmasek** [completecoding/serverless-auto-swagger#124]
This is my `./src/types/api-types.d.ts` file.

```typescript
import type { ScheduleRow } from 'schedule-client';

export type PersonScheduleType = ScheduleRow[];
```

and this is taken from the `serverless.yml` file.
```yml
  ...
  getPersonSchedule:
    timeout: 10
    handler: src/functions/getPersonSchedule.handler
    events:
      - httpApi:
          summary: 'Get person schedule'
          description: 'Get the schedule of a courseEvent'
          swaggerTags: ['Person']
          path: /person/{personId}/schedule
          method: get
          responseData:
            200:
              bodyType: 'PersonScheduleType'
  ...
```

This results in the following error.

`Could not resolve reference: Could not resolve pointer: /definitions/ScheduleRow does not exist in document`

I wonder if someone's been able to use type definitions from external libraries?
