### ISSUE TITLE
Request schemas of body for PUT/POST

### ISSUE THREAD

**Issue by VladislavLobakh** [completecoding/serverless-auto-swagger#82]
Hello! Is it possible somehow to parse request schema instead of manually defining bodyType?
It will be really nice feature and I guess it's more appropriate behavior.

serverless.yml:
```
request:
  schemas:
    application/json: ${file(product-schema.json)}
# bodyType: 'CreateProduct'
```
