### ISSUE TITLE
Allow use of 'serverless-http' when reading functions

### ISSUE THREAD

**Issue by SebaSOFT** [completecoding/serverless-auto-swagger#85]
Sample serverless.yml
```
...
functions:
  app:
    handler: app.serverless # reference the file and exported method
    events:
      - http:
          path: / # this matches the base path
          method: ANY
      - http:
          path: /{proxy+} # this matches any path, the token 'any' doesn't mean anything special
          method: ANY
``` 
and then on `app.js`
```
const sls = require('serverless-http');
...
...
...
module.exports = app;
module.exports.serverless = sls(app);
```

the `sls generate-swagger` will generate a json description that looks like this:
```
{
  "swagger": "2.0",
  "info": {
    "title": "swagger",
    "version": "1"
  },
  "paths": {
    "/": {
      "any": {
        "summary": "app",
        "description": "",
        "operationId": "app.any./",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        },
        "security": [
          {
            "Authorization": [],
            "x-api-key": []
          }
        ]
      }
    },
    "/{proxy+}": {
      "any": {
        "summary": "app",
        "description": "",
        "operationId": "app.any./{proxy+}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "proxy+",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        },
        "security": [
          {
            "Authorization": [],
            "x-api-key": []
          }
        ]
      }
    }
  },
  "definitions": {},
  "securityDefinitions": {
    "Authorization": {
      "type": "apiKey",
      "name": "Authorization",
      "in": "header"
    },
    "x-api-key": {
      "type": "apiKey",
      "name": "x-api-key",
      "in": "header"
    }
  },
  "basePath": "/"
}
```

Tested with node/lambda
